@echo off
title 16gb
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 