@echo off
title 8gb
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start msedge.exe 
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe
start calc.exe